SELECT *
  FROM USER_TABLES;
  
 
SELECT STUD_ID AS studId, NAME, EMAIL, DOB, PHONE 
  FROM STUDENTS
 WHERE STUD_ID = 1;
 
select stud_id, name, email, dob,
               substr(phone, 1, 3) as f, 
               substr(phone, 5, 3) as m, 
               substr(phone, 9, 4) as l
  from students 
 where stud_id = 1;
 
-- 일대일 매핑
SELECT STUD_ID, NAME, EMAIL, PHONE, DOB, A.ADDR_ID, STREET, CITY, STATE, ZIP, COUNTRY
  FROM STUDENTS S JOIN ADDRESSES A ON S.ADDR_ID=A.ADDR_ID
 WHERE STUD_ID = 1; 


SELECT T.TUTOR_ID, T.NAME AS TUTOR_NAME, EMAIL, C.COURSE_ID, C.NAME, DESCRIPTION, START_DATE, END_DATE
  FROM TUTORS T LEFT OUTER JOIN COURSES C ON T.TUTOR_ID=C.TUTOR_ID
 WHERE T.TUTOR_ID =1;


SELECT STUD_ID, NAME, EMAIL, DOB, PHONE, gender 
  FROM STUDENTS
 WHERE STUD_ID > 2;